### ISSUE TITLE
Unknown Protocol: DEVICE

### ISSUE THREAD

**Issue by nbdy** [howdydoody123/KismetPiDisplay#1]
Apparently it does not work with the kismetclient anymore.
There is no Protocol DEVICE.
Or am I doing something wrong?

![](http://i.imgur.com/wwMBzYF.png)

**Comment by howdydoody123** [comment]
What are the steps you followed to set everything up?

**Comment by nbdy** [comment]
Cloned & installed Kismetclient.
Cloned & installed Kismet itself.
Installed dependencies.

Also:

> > k.protocols.keys()
> > ['CRITFAIL', 'ACK', 'PACKET', 'NETTAG', 'BTSCANDEV', 'CAPABILITY',
> > 'SOURCE', 'COMMON', 'CLISRC', 'TRACKINFO', 'PROTOCOLS', 'BSSIDSRC',
> > 'STATUS', 'WEPKEY', 'STRING', 'SPECTRUM', 'ERROR', 'CHANNEL', 'GPS',
> > 'INFO', 'SSID', 'BSSID', 'PLUGIN', 'BATTERY', 'TERMINATE', 'REMOVE',
> > 'ALERT', 'KISMET', 'CLIENT', 'TIME', 'CLITAG']
> > #> No Protocol 'DEVICE'

**Comment by howdydoody123** [comment]
It might be a little while before I have time to look at this. I'll try doing everything from scratch again and see if I can reproduce a successful result.

**Comment by nbdy** [comment]
Going to try it with older versions of kismet. Seems like the protocol has changed.
If I can make it work again, I'll let you know.
